// ==UserScript==
// @name         Cosmic Cat
// @namespace    https://www.youtube.com/*
// @version      0.8
// @description  Broadcast Yourself
// @author       Thistle Café, Cosmic Cat Maintainers
// @updateURL    https://raw.githubusercontent.com/cosmic-cat-yt/cosmic-cat/main/cosmic-cat.user.js
// @downloadURL  https://raw.githubusercontent.com/cosmic-cat-yt/cosmic-cat/main/cosmic-cat.user.js
// @license      The Unlicense
// @match        https://www.youtube.com/*
// @exclude      https://www.youtube.com/embed/*
// @exclude      https://www.youtube.com/live_chat*
// @icon         https://github.com/cosmic-cat-yt/cosmic-cat-branding/raw/main/icon.png
// @require      https://code.jquery.com/jquery-3.6.1.min.js
// @grant unsafeWindow
// @grant GM_addStyle
// @grant GM.getValue
// @grant GM.setValue
// @grant GM_xmlhttpRequest
// @grant GM_registerMenuCommand
// @grant GM_deleteValue
// @grant GM_listValues
// @grant GM_getResourceText
// @grant GM_getResourceURL
// @grant GM_log
// @grant GM_openInTab
// @grant GM_setClipboard
// @grant GM_info
// @run-at document-start
// ==/UserScript==

// Generated by compile script. See GitHub for source code.
// https://github.com/cosmic-cat-yt/cosmic-cat

